name: work

# Triggers for when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  Build-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          clean: false
      - name: Clean working directory
        run: rm -rf ${{ github.workspace }}/*
        shell: bash

  build:
    name: test-action
    runs-on: ubuntu-latest
    needs:
      - Build-Build
    environment:
      name: approval_required
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
